/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;
	import ChartControl;

	public class ChartViewUI extends Scene {
		public var newgroup:Label;
		public var todayOrderNun:Label;
		public var todayOrderAmount:Label;
		public var monthyOrderAmount:Label;
		public var areaList:List;
		public var outputlist:List;
		public var materialBox:Box;
		public var monthBox:Box;
		public var tendayBox:Box;
		public var hourBox:Box;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("ChartView");

		}

	}
}