/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;

	public class DataGridViewUI extends View {
		public var btmline:Sprite;
		public var seq:Label;
		public var nametxt:Label;
		public var amount:Label;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{},"compId":2,"child":[{"type":"Sprite","props":{"y":0,"x":0,"scaleY":0.8,"scaleX":1.6},"compId":10,"child":[{"type":"Line","props":{"y":0,"x":4.5,"toY":0,"toX":300,"lineWidth":1,"lineColor":"#ABECD7"},"compId":3},{"type":"Line","props":{"y":0,"x":4.5,"toY":34,"toX":0,"lineWidth":0.7,"lineColor":"#ABECD7"},"compId":6},{"type":"Line","props":{"y":0,"x":80,"toY":35,"toX":0,"lineWidth":0.7,"lineColor":"#ABECD7"},"compId":7},{"type":"Line","props":{"y":0,"x":304.6,"toY":34,"toX":0,"lineWidth":0.6,"lineColor":"#ABECD7"},"compId":8},{"type":"Line","props":{"y":0,"x":230,"toY":35,"toX":0,"lineWidth":0.7,"lineColor":"#ABECD7"},"compId":9}]},{"type":"Sprite","props":{"y":27,"x":6,"var":"btmline","scaleX":1.6},"compId":14,"child":[{"type":"Line","props":{"y":0,"x":0,"toY":0,"toX":300,"lineWidth":1,"lineColor":"#ABECD7"},"compId":5}]},{"type":"Label","props":{"y":0,"x":10,"width":106,"var":"seq","valign":"middle","text":"12","height":26,"fontSize":18,"color":"#ece4e4","align":"center"},"compId":11},{"type":"Label","props":{"y":0,"x":129,"width":234,"var":"nametxt","valign":"middle","text":"浙江物语喷印","height":26,"fontSize":18,"color":"#ece4e4","align":"center"},"compId":12},{"type":"Label","props":{"y":0,"x":372,"width":108,"var":"amount","valign":"middle","text":"39689696.96","height":26,"fontSize":18,"color":"#ece4e4","align":"center"},"compId":13}],"loadList":[],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}